baseurl: 'https://www.baggedandboosted.com/'
buildFuture: true
blackfriday:
  plainIdAnchors: true
theme: story
googleAnalytics: "UA-138046739-1"
title: "Bagged and Boosted"
menu:
   main:
   - name: Archives
     title: Archives
     url: /archives/
   social:
   - name: linkedin
     title: "fab fa-linkedin"
     url: "https://linkedin.com/in/jhlch"
   - name: twitter
     title: "fab fa-twitter-square"
     url: "https://twitter.com/j_houg"
   - name: github
     title: "fab fa-github-square"
     url: "https://github.com/hougs"
params:
   author: "Juliet Hougland"
   twitter: "j_houg"
   mailchimp: "https://mailchi.mp/3055cefc0d84/baggedandboosted"
   email: "&#106;&#117;&#108;&#105;&#101;&#116;&#64;&#98;&#97;&#103;&#103;&#101;&#100;&#97;&#110;&#100;&#98;&#111;&#111;&#115;&#116;&#101;&#100;&#46;&#99;&#111;&#109;"
   titlecase: true
   classes:
   - feature-math
   - feature-figcaption
   - feature-tablecaption
   - feature-figcaption-hidden
   - feature-3dbook-covers
   - feature-hyphenate
   - feature-justify
   - feature-highlight
   - feature-hrfleuron
   - feature-qrcode
   - feature-tweetquote
   - feature-depth
MetaDataFormat: "yaml"
Paginate: 20
rssLimit: 20
Taxonomies:
   category: "categories"
   tag: "tags"
outputs:
   home:
      - HTML
      - JSON
      - RSS
   page:
      - HTML
   section:
      - HTML
      - RSS
   taxonomy:
      - HTML
      - RSS
   taxonomyTerm:
      - HTML
      - RSS
Related:
   threshold: 50
   toLower: true
   indices:
      - name: keywords
        weight: 100
      - name: categories
        weight: 50
      - name: description
        weight: 50
      - name: title
        weight: 100
---
